import React from 'react'
import styles from './Layout.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import parse from 'html-react-parser'
import { PageQuery } from '../../__generated__/graphql'

// const Layout = ({articles}) => {
const Layout = (props: PageQuery['pages'][0]) => {
  const { articles } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {articles.map(({ html }, index) => (
          <article key={index} className={styles.article}>
            {parse(html)}
          </article>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Layout
