import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useQuery, ApolloClient, InMemoryCache } from '@apollo/client'
import { GET_HOMEPAGE_QUERY } from '../src/queries'
import { GetHomePageQuery } from '../src/__generated__/graphql'
import parse from 'html-react-parser'

const Home = (props?: GetHomePageQuery['pages'][0]) => {
  if (props) {
    const { articles } = props

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          {articles.map(({ html }) => (
            <article className={styles.article}>{parse(html)}</article>
          ))}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    )
  }

  return null
}

// SSG
export async function getStaticProps() {
  // Get static props
  const client = new ApolloClient({
    uri: process.env.HYGRAPH_ENDPOINT,
    cache: new InMemoryCache(),
  })

  const { data } = await client.query({
    query: GET_HOMEPAGE_QUERY,
  })

  return {
    props: {
      ...data?.pages[0],
    },
  }
}

export default Home
